LabelName$(0) = "lblRS232" : XPos(0) = 271: YPos(0) = 105: Wdh(0) = 80: Height(0) = 14

LabelName$(1) = "lblFrame" : XPos(1) = 272: YPos(1) = 130: Wdh(1) = 332: Height(1) = 210

LabelName$(30) = "lbldevicenum" : XPos(30) = 297: YPos(30) = 156: Wdh(30) = 80: Height(30) =15
LabelName$(2) = "lblbaudrate" : XPos(2) = 297: YPos(2) = 181: Wdh(2) = 80: Height(2) = 15
LabelName$(3) = "lbldatabit" : XPos(3) = 297: YPos(3) = 206: Wdh(3) = 80: Height(3) = 15
LabelName$(4) = "lblstopbit" : XPos(4) = 297: YPos(4) = 231: Wdh(4) = 80: Height(4) = 15
LabelName$(5) = "lblparitycheck" : XPos(5) = 297: YPos(5) = 256: Wdh(5) = 80: Height(5) = 15
LabelName$(6) = "lblstreamcontrol" : XPos(6) = 297: YPos(6) = 281: Wdh(6) = 90: Height(6) = 15
LabelName$(7) = "lblapplyto" : XPos(7) = 297: YPos(7) = 313: Wdh(7) = 80: Height(7) = 15

LabelName$(31) = "ddDeviceNum" : XPos(31) = 406: YPos(31) = 156: Wdh(31) = 150: Height(31) = -1
LabelName$(8) = "ddBaudRate" : XPos(8) = 407: YPos(8) = 181: Wdh(8) = 150: Height(8) = -1
LabelName$(9) = "ddDataBit" : XPos(9) = 407: YPos(9) = 206: Wdh(9) = 150: Height(9) = -1
LabelName$(10) = "ddStopBit" : XPos(10) = 407: YPos(10) = 231: Wdh(10) = 150: Height(10) = -1
LabelName$(11) = "ddParityCheck" : XPos(11) = 407: YPos(11) = 256: Wdh(11) = 150: Height(11) = -1
LabelName$(12) = "ddStreamControl" : XPos(12) = 407: YPos(12) = 281: Wdh(12) = 150: Height(12) = -1
LabelName$(13) = "ddApplyTo" : XPos(13) = 407: YPos(13) = 313: Wdh(13) = 150: Height(13) = -1






LabelName$(14) = "lblRS485" : XPos(14) = 645: YPos(14) = 105: Wdh(14) = 80: Height(14) = 14

LabelName$(15) = "lblFrame1" : XPos(15) = 646: YPos(15) = 130: Wdh(15) = 332: Height(15) = 210

LabelName$(21) = "lbldevicenum1" : XPos(21) = 669: YPos(21) = 144: Wdh(21) = 80: Height(21) = 15
LabelName$(16) = "lblstreamcontrol1" : XPos(16) = 670: YPos(16) = 169: Wdh(16) = 80: Height(16) = 15
LabelName$(17) = "lblbaudrate1" : XPos(17) = 670: YPos(17) = 194: Wdh(17) = 80: Height(17) = 15
LabelName$(18) = "lbldatabit1" : XPos(18) = 670: YPos(18) = 219: Wdh(18) = 80: Height(18) = 15
LabelName$(19) = "lblstopbit1" : XPos(19) = 670: YPos(19) = 244: Wdh(19) = 80: Height(19) = 15
LabelName$(20) = "lblparitycheck1" : XPos(20) = 670: YPos(20) = 269: Wdh(20) = 80: Height(20) = 15
//LabelName$(21) = "lblstreamcontrol1" : XPos(21) = 670: YPos(21) = 294: Wdh(21) = 90: Height(21) = 15
//LabelName$(22) = "lbldecoderaddr1" : XPos(22) = 670: YPos(22) = 321: Wdh(22) = 80: Height(22) = 15
//LabelName$(36) = "lbldeal" : XPos(36) = 670: YPos(36) = 344: Wdh(36) = 80: Height(36) = 25//by wbb

LabelName$(22) = "ddDeviceNum1" : XPos(22) = 780: YPos(22) = 144: Wdh(22) = 150: Height(22) = -1
LabelName$(23) = "ddStreamControl1" : XPos(23) = 781: YPos(23) = 169: Wdh(23) = 150: Height(23) = -1
LabelName$(24) = "ddBaudRate1" : XPos(24) = 781: YPos(24) = 194: Wdh(24) = 150: Height(24) = -1
LabelName$(25) = "ddDataBit1" : XPos(25) = 781: YPos(25) = 219: Wdh(25) = 150: Height(25) = -1
LabelName$(26) = "ddStopBit1" : XPos(26) = 781: YPos(26) = 244: Wdh(26) = 150: Height(26) = -1
LabelName$(27) = "ddParityCheck1" : XPos(27) = 781: YPos(27) = 269: Wdh(27) = 150: Height(27) = -1
//LabelName$(28) = "ddStreamControl1" : XPos(28) = 781: YPos(28) = 294: Wdh(28) = 150: Height(28) = -1
//LabelName$(29) = "txtdecoderaddr1" : XPos(29) = 781: YPos(29) = 321: Wdh(29) = 155: Height(29) = -1
//LabelName$(37) = "ddDeal" : XPos(37) = 781: YPos(37) = 344: Wdh(37) = 80: Height(37) = 26//by wbb

LabelName$(28) = "btnSave" : XPos(28) = 523: YPos(28) = 370: Wdh(28) = 80: Height(28) = 20
LabelName$(29) = "btncancel" : XPos(29) = 644: YPos(29) = 370: Wdh(29) = 80: Height(29) = 20





