LabelName$(21) = "drpchannel" : XPos(21) = 450: YPos(21) = 165: Wdh(21) = 100: Height(21) = -1
LabelName$(3) = "Textid" : XPos(3) = 720: YPos(3) = 130: Wdh(3) = 100: Height(3) = -1
LabelName$(4) = "drptype" : XPos(4) = 720: YPos(4) = 165: Wdh(4) = 100: Height(4) = -1
LabelName$(5) = "Textplc" : XPos(5) = 720: YPos(5) = 195: Wdh(5) = 100: Height(5) = -1
LabelName$(6) = "Textadd" : XPos(6) = 720: YPos(6) = 225: Wdh(6) = 100: Height(6) = -1
LabelName$(7) = "Textnum" : XPos(7) = 720: YPos(7) = 255: Wdh(7) = 100: Height(7) = -1
LabelName$(1) = "Textip" : XPos(1) = 720: YPos(1) = 285: Wdh(1) = 120: Height(1) = 14
LabelName$(2) = "Textport" : XPos(2) = 450: YPos(2) = 225: Wdh(2) = 100: Height(2) = -1
LabelName$(12) = "btnFrameOK" : XPos(12) = 520: YPos(12) = 603: Wdh(12) = 120: Height(12) = 40
LabelName$(13) = "btnFrameCancel" : XPos(13) = 650: YPos(13) = 603: Wdh(13) = 120: Height(13) = 40
LabelName$(14) = "optSelect" : XPos(14) = 400: YPos(14) = 75: Wdh(14) = 113: Height(14) = 14

LabelName$(15) = "lbluseto" : XPos(15) = 350: YPos(15) = 130: Wdh(15) = 80: Height(15) = 14
LabelName$(16) = "optSelectTcp" : XPos(16) = 700: YPos(16) = 75: Wdh(16) = 113: Height(16) = 14
LabelName$(17) = "lblFrame" : XPos(17) = 340: YPos(17) = 105: Wdh(17) = 500: Height(17) = 600
LabelName$(22) = "lbchannel" : XPos(22) = 350: YPos(22) = 165: Wdh(22) = 80: Height(22) = 14
LabelName$(8) = "lblid" : XPos(8) = 620: YPos(8) = 130: Wdh(8) = 80: Height(8) = 14

LabelName$(9) = "lbldatatype" : XPos(9) = 620: YPos(9) = 165: Wdh(9) = 80: Height(9) = 14
LabelName$(10) = "lblplc" : XPos(10) = 620: YPos(10) = 195: Wdh(10) = 80: Height(10) = 14
LabelName$(11) = "lbladd" : XPos(11) = 620: YPos(11) = 225: Wdh(11) = 80: Height(11) = 14
LabelName$(20) = "lblnum" : XPos(20) = 620: YPos(20) = 255: Wdh(20) = 80: Height(20) = 14
LabelName$(18) = "lblip" : XPos(18) = 620: YPos(18) = 285: Wdh(18) = 80: Height(18) = 14
LabelName$(19) = "lblport" : XPos(19) = 350: YPos(19) = 225: Wdh(19) = 80: Height(19) = 14

LabelName$(0) = "drpuseto" : XPos(0) = 450: YPos(0) = 130: Wdh(0) = 100: Height(0) = -1

LabelName$(23) = "lblprotocol" : XPos(23) = 350: YPos(23) = 195: Wdh(23) = 80: Height(23) = 25
LabelName$(24) = "lblbaudrate1" : XPos(24) = 350: YPos(24) = 335: Wdh(24) = 80: Height(24) = 25
LabelName$(25) = "lbldatabit1" : XPos(25) = 350: YPos(25) = 365: Wdh(25) = 80: Height(25) = 25
LabelName$(26) = "lblstopbit1" : XPos(26) = 350: YPos(26) = 395: Wdh(26) = 80: Height(26) = 25
LabelName$(27) = "lblparitycheck1" : XPos(27) = 350: YPos(27) = 425: Wdh(27) = 80: Height(27) = 25
LabelName$(28) = "lblstreamcontrol1" : XPos(28) = 350: YPos(28) = 455: Wdh(28) = 80: Height(28) = 25

LabelName$(29) = "drpprotocol" : XPos(29) = 450: YPos(29) = 195: Wdh(29) = 100: Height(29) = -1
LabelName$(30) = "ddBaudRate1" : XPos(30) = 450: YPos(30) = 335: Wdh(30) = 100: Height(30) = 25
LabelName$(31) = "ddDataBit1" : XPos(31) = 450: YPos(31) = 365: Wdh(31) = 100: Height(31) = 25
LabelName$(32) = "ddStopBit1" : XPos(32) = 450: YPos(32) = 395: Wdh(32) = 100: Height(32) = 25
LabelName$(33) = "ddParityCheck1" : XPos(33) = 450: YPos(33) = 425: Wdh(33) = 100: Height(33) = 25
LabelName$(34) = "ddStreamControl1" : XPos(34) = 450: YPos(34) = 455: Wdh(34) = 100: Height(34) = 25

LabelName$(35) = "lbpoll" : XPos(35) = 350: YPos(35) = 255: Wdh(35) = 80: Height(35) = 25
LabelName$(36) = "lbexpire" : XPos(36) = 350: YPos(36) = 285: Wdh(36) = 80: Height(36) = 25
LabelName$(37) = "Textpoll" : XPos(37) = 450: YPos(37) = 255: Wdh(37) = 100: Height(37) = 25
LabelName$(38) = "Textexpire" : XPos(38) = 450: YPos(38) = 285: Wdh(38) = 100: Height(38) = 25


