'LabelName$(0) = "ddStream" : XPos(0) = 352: YPos(0) = 70: Wdh(0) = 111: Height(0) = -1
'LabelName$(1) = "chkDispallstreams" : XPos(1) = : YPos(1) = 80: Wdh(1) = 144: Height(1) = 14
'LabelName$(2) = "ddExample" : XPos(2) = 845: YPos(2) = 70: Wdh(2) = 111: Height(2) = -1
LabelName$(0) = "gdobg5" : XPos(0) = 320: YPos(0) = 220: Wdh(0) = 480: Height(0) = 380
LabelName$(1) = "imgaudio" : XPos(1) = 850: YPos(1) = 530: Wdh(1) = 40: Height(1) = 40
LabelName$(2) = "imgalarm" : XPos(2) = 896: YPos(2) = 530: Wdh(2) = 40: Height(2) = 40
LabelName$(3) = "imgrecord" : XPos(3) = 942: YPos(3) = 530: Wdh(3) = 40: Height(3) = 40
LabelName$(4) = "imgsnap" : XPos(4) = 988: YPos(4) = 530: Wdh(4) = 40: Height(4) = 40
LabelName$(5) = "gdobg1" : XPos(5) = 258: YPos(5) = 70: Wdh(5) = 270: Height(5) = 210

LabelName$(6) = "lblSelectChannel" : XPos(6) = 259: YPos(6) = 80: Wdh(6) = 86: Height(6) = 14
'LabelName$(9) = "lblExample" : XPos(9) = 780: YPos(9) = 70: Wdh(9) = 57: Height(9) = 14

LabelName$(7) = "frmSnap" : XPos(7) = 540: YPos(7) = 530: Wdh(7) = 398: Height(7) = 80
LabelName$(8) = "imgsdCard" : XPos(8) = 783: YPos(8) = 70: Wdh(8) = 40: Height(8) = 40
//LabelName$(9) = "imgDisplay1x" : XPos(9) = 840: YPos(9) = 596: Wdh(9) = 66: Height(9) = 48
LabelName$(9) = "imgDisplay1x" : XPos(9) = 540: YPos(9) = 566: Wdh(9) = 66: Height(9) = 48


LabelName$(10) = "txtSnapText" : XPos(10) = 654: YPos(10) = 560: Wdh(10) = 213: Height(10) = -1
LabelName$(11) = "optStorage" : XPos(11) = 654: YPos(11) = 593: Wdh(11) = 83: Height(11) = 14
LabelName$(12) = "optStorage[1]" : XPos(12) = 756: YPos(12) = 593: Wdh(12) = 55: Height(12) = 14
LabelName$(13) = "optStorage[2]" : XPos(13) = 808: YPos(13) = 593: Wdh(13) = 62: Height(13) = 14
LabelName$(14) = "btnOk" : XPos(14) = 875: YPos(14) = 565: Wdh(14) = 57: Height(14) = 20
LabelName$(15) = "btnCancel" : XPos(15) = 875: YPos(15) = 593: Wdh(15) = 57: Height(15) = 20
LabelName$(16) = "lblSnapText" : XPos(16) = 552: YPos(16) = 565: Wdh(16) = 98: Height(16) = 14
LabelName$(17) = "lblSaveTo" : XPos(17) = 552: YPos(17) = 593: Wdh(17) = 56: Height(17) = 14

LabelName$(18) = "lblLoad" : XPos(18) = 564: YPos(18) = 273: Wdh(18) = 192: Height(18) = 31
LabelName$(19) = "gdobg2" : XPos(19) = 553: YPos(19) = 190: Wdh(19) = 270: Height(19) = 210
LabelName$(20) = "gdobg3" : XPos(20) = 258: YPos(20) = 410: Wdh(20) = 270: Height(20) = 210
LabelName$(21) = "gdobg4" : XPos(21) = 553: YPos(21) = 410: Wdh(21) = 270: Height(21) = 210

LabelName$(22) = "imgyuntai" : XPos(22) = 420: YPos(22) = 530: Wdh(22) = 100: Height(22) = 80

LabelName$(53) = "yuzhidian" : XPos(53) = 900: YPos(53) = 530: Wdh(53) = 50: Height(53) = 20
LabelName$(54) = "setbtn" : XPos(54) =840: YPos(54) = 580: Wdh(54) = 40: Height(54) = 30
LabelName$(55) = "usebtn" : XPos(55) =900: YPos(55) = 580: Wdh(55) = 40: Height(55) = 30
LabelName$(56) = "note" : XPos(56) =900: YPos(56) = 555: Wdh(56) = 60: Height(56) = 30
LabelName$(57) = "lablepreset" : XPos(57) =840: YPos(57) = 530: Wdh(57) = 50: Height(57) = 20
LabelName$(58) = "Labeldescribe" : XPos(58) =840: YPos(58) = 555: Wdh(58) = 50: Height(58) = 20




LabelName$(25) = "imgjjd" : XPos(25) = 690: YPos(25) = 530: Wdh(25) = 45: Height(25) =33
LabelName$(26) = "ljiaoju" : XPos(26) = 720: YPos(26) =540: Wdh(26) = 45: Height(26) =14
LabelName$(27) = "imgjjx" : XPos(27) = 760: YPos(27) = 530: Wdh(27) = 45: Height(27) = 33

LabelName$(28) = "yuntaichannel" : XPos(28) = 250: YPos(28) =580: Wdh(28) = 80: Height(28) = 18
LabelName$(29) = "channelNum" : XPos(29) = 330: YPos(29) =615: Wdh(29) = 40: Height(29) = -1


//LabelName$(30) = "imgjdy" : XPos(30) = 690: YPos(30) = 596: Wdh(30) = 45: Height(30) = 33
//LabelName$(31) = "ljiaodian" : XPos(31) = 720: YPos(31) =606 : Wdh(31) = 45: Height(31) = 14
//LabelName$(32) = "imgjdj" : XPos(32) = 760: YPos(32) =596: Wdh(32) = 45: Height(32) = 33

LabelName$(30) = "imgjdy" : XPos(30) = 690: YPos(30) = 566: Wdh(30) = 45: Height(30) = 33
LabelName$(31) = "ljiaodian" : XPos(31) = 720: YPos(31) =576 : Wdh(31) = 45: Height(31) = 14
LabelName$(32) = "imgjdj" : XPos(32) = 760: YPos(32) =566: Wdh(32) = 45: Height(32) = 33

//LabelName$(33) = "imggqd" : XPos(33) = 540: YPos(33) =596: Wdh(33) = 45: Height(33) = 33
//LabelName$(34) = "lguangquan" : XPos(34) = 565: YPos(34) =606: Wdh(34) = 57: Height(34) = 14
//LabelName$(35) = "imggqx" : XPos(35) = 610: YPos(35) =596: Wdh(35) = 45: Height(35) = 33

LabelName$(33) = "imggqd" : XPos(33) = 690: YPos(33) =602: Wdh(33) = 45: Height(33) = 33
LabelName$(34) = "lguangquan" : XPos(34) = 720: YPos(34) =612: Wdh(34) = 57: Height(34) = 14
LabelName$(35) = "imggqx" : XPos(35) = 760: YPos(35) =602: Wdh(35) = 45: Height(35) = 33


LabelName$(36) = "imgdg" : XPos(36) = 540: YPos(36) =530: Wdh(36) = 45: Height(36) = 33
LabelName$(37) = "imgysh" : XPos(37) = 610: YPos(37) =530: Wdh(37) = 45: Height(37) = 33


LabelName$(38) = "strchannel" : XPos(38) = 250: YPos(38) =530: Wdh(38) = 80: Height(38) = 18

LabelName$(39) = "streamChannel" : XPos(39) = 330: YPos(39) =530: Wdh(39) = 40: Height(39) = -1



LabelName$(40) = "imgplayrecord" : XPos(40) = 506: YPos(40) = 70: Wdh(40) = 40: Height(40) = 40


LabelName$(41) = "Channel1" : XPos(41) = 332: YPos(41) = 80: Wdh(41) = 20: Height(41) = 14
LabelName$(42) = "Channel2" : XPos(42) = 360:YPos(42) = 80: Wdh(42) = 20: Height(42) = 14
LabelName$(43) = "Channel3" : XPos(43) = 388: YPos(43) = 80: Wdh(43) = 20: Height(43) = 14
LabelName$(23) = "Channel4" : XPos(23) = 416: YPos(23) = 80: Wdh(23) = 20: Height(23) = 14

LabelName$(24) = "recordOk" : XPos(24) = 440: YPos(24) = 80: Wdh(24) = 50: Height(24) = 20
//LabelName$(46) = "recordOk" : XPos(46) = 258: YPos(46) = 70: Wdh(46) = 50: Height(46) = 20

LabelName$(44) = "RadstreamChannel" : XPos(44) = 250: YPos(44) = 550: Wdh(44) = 40 :Height(44) =10
LabelName$(45) = "RadstreamChannel[1]" : XPos(45) = 290: YPos(45) = 550: Wdh(45) = 30 :Height(45) =10
LabelName$(46) = "RadstreamChannel[2]" : XPos(46) = 320: YPos(46) = 550: Wdh(46) = 30 :Height(46) =10
LabelName$(47) = "RadstreamChannel[3]" : XPos(47) = 350: YPos(47) = 550: Wdh(47) = 30 :Height(47) =10
LabelName$(48) = "RadstreamChannel[4]" : XPos(48) = 380: YPos(48) = 550: Wdh(48) = 30 :Height(48) =10

LabelName$(49) = "RadchannelNum" : XPos(49) =250: YPos(49) = 600: Wdh(49) =30: Height(49)=10
LabelName$(50) = "RadchannelNum[1]" : XPos(50) =280: YPos(50) = 600: Wdh(50) =30: Height(50)=10
LabelName$(51) = "RadchannelNum[2]" : XPos(51) =310: YPos(51) = 600: Wdh(51) =30: Height(51)=10
LabelName$(52) = "RadchannelNum[3]" : XPos(52) =340: YPos(52) = 600: Wdh(52) =30: Height(52)=10