LabelName$(0) = "gdobg1" : XPos(0) = 258: YPos(0) = 80: Wdh(0) = 690: Height(0) = 480
'LabelName$(1) = "gdobg2" : XPos(1) = 553: YPos(1) = 80: Wdh(1) = 270: Height(1) = 210
'LabelName$(2) = "gdobg3" : XPos(2) = 258: YPos(2) = 300: Wdh(2) = 270: Height(2) = 210
'LabelName$(3) = "gdobg4" : XPos(3) = 553: YPos(3) = 300: Wdh(3) = 270: Height(3) = 210
LabelName$(4) = "imgsearch" : XPos(4) = 870: YPos(4) = 200: Wdh(4) = 100: Height(4) =18
LabelName$(5) = "strchannel" : XPos(5) = 845: YPos(5) = 80: Wdh(5) = 53: Height(5) =18
LabelName$(6) = "streamChannel" : XPos(6) = 915: YPos(6) = 80: Wdh(6) = 70: Height(6) = -1
LabelName$(7) = "lbltime" : XPos(7) = 845: YPos(7) = 120: Wdh(7) = 62: Height(7) = 18
LabelName$(8) = "recorddate" : XPos(8) = 915: YPos(8) = 120: Wdh(8) = 76: Height(8) = -1

LabelName$(9) = "imgplay" : XPos(9) = 853: YPos(9) = 250: Wdh(9) = 66: Height(9) = 48
LabelName$(10) = "imgstop" : XPos(10) = 943: YPos(10) = 250: Wdh(10) = 66: Height(10) = 48
LabelName$(11) = "imgpause" : XPos(11) = 853: YPos(11) = 320: Wdh(11) = 66: Height(11) = 48



LabelName$(12) = "playslider" : XPos(12) = 258: YPos(12) = 620: Wdh(12) =560: Height(12) = 14
//LabelName$(13) = "Label2" : XPos(13) = 286: YPos(13) = 535: Wdh(13) =20: Height(13) = 10
LabelName$(13) = "Label2" : XPos(13) = 286: YPos(13) = 555: Wdh(13) =20: Height(13) = 10
LabelName$(14) = "Label3" : XPos(14) = 309: YPos(14) = 555: Wdh(14) =20: Height(14) = 10
LabelName$(15) = "Label4" : XPos(15) = 332: YPos(15) = 555: Wdh(15) =20: Height(15) = 10
LabelName$(16) = "Label5" : XPos(16) = 355: YPos(16) = 555: Wdh(16) =20: Height(16) = 10
LabelName$(17) = "Label6" : XPos(17) = 378: YPos(17) =555: Wdh(17) =20: Height(17) = 10
LabelName$(18) = "Label7" : XPos(18) = 401: YPos(18) = 555: Wdh(18) =20: Height(18) = 10
LabelName$(19) = "Label8" : XPos(19) = 424: YPos(19) = 555: Wdh(19) =20: Height(19) = 10
LabelName$(20) = "Label9" : XPos(20) = 447: YPos(20) = 555: Wdh(20) =20: Height(20) = 10
LabelName$(21) = "Label10" : XPos(21) = 470: YPos(21) = 555: Wdh(21) =20: Height(21) = 10
LabelName$(22) = "Label11" : XPos(22) = 493: YPos(22) = 555: Wdh(22) =20: Height(22) = 10
LabelName$(23) = "Label12" : XPos(23) = 515: YPos(23) = 555: Wdh(23) =20: Height(23) = 10
LabelName$(24) = "Label13" : XPos(24) = 538: YPos(24) = 555: Wdh(24) =20: Height(24) = 10
LabelName$(25) = "Label14" : XPos(25) = 561: YPos(25) = 555: Wdh(25) =20: Height(25) = 10
LabelName$(26) = "Label15" : XPos(26) = 584: YPos(26) = 555: Wdh(26) =20: Height(26) = 10
LabelName$(27) = "Label16" : XPos(27) = 607: YPos(27) = 555: Wdh(27) =20: Height(27) = 10
LabelName$(28) = "Label17" : XPos(28) = 630: YPos(28) = 555: Wdh(28) =20: Height(28) = 10
LabelName$(29) = "Label18" : XPos(29) = 653: YPos(29) = 555: Wdh(29) =20: Height(29) = 10
LabelName$(30) = "Label19" : XPos(30) = 676: YPos(30) = 555: Wdh(30) =20: Height(30) = 10
LabelName$(31) = "Label20" : XPos(31) = 699: YPos(31) = 555: Wdh(31) =20: Height(31) = 10
LabelName$(32) = "Label21" : XPos(32) = 722: YPos(32) = 555: Wdh(32) =20: Height(32) = 10
LabelName$(33) = "Label22" : XPos(33) = 745: YPos(33) = 555: Wdh(33) =20: Height(33) = 10
LabelName$(34) = "Label23" : XPos(34) = 768: YPos(34) = 555: Wdh(34) =20: Height(34) = 10
LabelName$(35) = "Label24" : XPos(35) = 791: YPos(35) = 555: Wdh(35) =20: Height(35) = 10
LabelName$(36) = "Label1" : XPos(36) = 263: YPos(36) = 555: Wdh(36) =20: Height(36) = 10

LabelName$(37) = "imgresume" : XPos(37) = 943: YPos(37) = 320: Wdh(37) =66: Height(37) = 48
LabelName$(38) = "imgdisplayfull" : XPos(38) = 853: YPos(38) = 390: Wdh(38) = 66: Height(38) = 48
LabelName$(1) = "img2play" : XPos(1) = 943: YPos(1) = 390: Wdh(1) = 66: Height(1) = 48
LabelName$(2) = "img4play" : XPos(2) = 853: YPos(2) = 460: Wdh(2) = 66: Height(2) = 48
LabelName$(3) = "img8play" : XPos(3) = 943: YPos(3) = 460: Wdh(3) = 66: Height(3) = 48
LabelName$(39) = "img1play" : XPos(39) = 943: YPos(39) = 530: Wdh(39) = 66: Height(39) = 48
'LabelName$(40) = "Label25" : XPos(40) = 853: YPos(40) = 530: Wdh(40) = 66: Height(40) = 48