LabelName$(0) = "lblRS485" : XPos(0) = 443: YPos(0) = 105: Wdh(0) = 80: Height(0) = 14

LabelName$(1) = "lblFrame1" : XPos(1) = 444: YPos(1) = 130: Wdh(1) = 332: Height(1) = 300

LabelName$(2) = "lblchannelnum1" : XPos(2) = 469: YPos(2) = 144: Wdh(2) = 80: Height(2) = 25
LabelName$(3) = "lbldevicenum1" : XPos(3) = 470: YPos(3) = 169: Wdh(3) = 80: Height(3) = 25
LabelName$(4) = "lblbaudrate1" : XPos(4) = 470: YPos(4) = 194: Wdh(4) = 80: Height(4) = 25
LabelName$(5) = "lbldatabit1" : XPos(5) = 470: YPos(5) = 219: Wdh(5) = 80: Height(5) = 25
LabelName$(6) = "lblstopbit1" : XPos(6) = 470: YPos(6) = 244: Wdh(6) = 80: Height(6) = 25
LabelName$(7) = "lblparitycheck1" : XPos(7) = 470: YPos(7) = 269: Wdh(7) = 80: Height(7) = 25
LabelName$(8) = "lblstreamcontrol1" : XPos(8) = 470: YPos(8) = 294: Wdh(8) = 80: Height(8) = 25
LabelName$(9) = "lbldecoderaddr1" : XPos(9) = 470: YPos(9) = 319: Wdh(9) = 80: Height(9) = 25
LabelName$(20) = "lbldeal" : XPos(20) = 470: YPos(20) = 344: Wdh(20) = 80: Height(20) = 25//by wbb

LabelName$(10) = "ddChannelNum1" : XPos(10) = 605: YPos(10) = 144: Wdh(10) = 150: Height(10) = 26
LabelName$(11) = "ddDeviceNum1" : XPos(11) = 606: YPos(11) = 169: Wdh(11) = 150: Height(11) = 26
LabelName$(12) = "ddBaudRate1" : XPos(12) = 606: YPos(12) = 194: Wdh(12) = 150: Height(12) = 26
LabelName$(13) = "ddDataBit1" : XPos(13) = 606: YPos(13) = 219: Wdh(13) = 150: Height(13) = 26
LabelName$(14) = "ddStopBit1" : XPos(14) = 606: YPos(14) = 244: Wdh(14) = 150: Height(14) = 26
LabelName$(15) = "ddParityCheck1" : XPos(15) = 606: YPos(15) = 269: Wdh(15) = 150: Height(15) = 26
LabelName$(16) = "ddStreamControl1" : XPos(16) = 606: YPos(16) = 294: Wdh(16) = 150: Height(16) = 26
LabelName$(17) = "txtdecoderaddr1" : XPos(17) = 606: YPos(17) = 321: Wdh(17) = 155: Height(17) = 26
LabelName$(21) = "ddDeal" : XPos(21) = 606: YPos(21) = 344: Wdh(21) = 80: Height(21) = 26//by wbb

LabelName$(18) = "btnSave" : XPos(18) = 543: YPos(18) = 618: Wdh(18) = 80: Height(18) = 20
LabelName$(19) = "btncancel" : XPos(19) = 630: YPos(19) = 618: Wdh(19) = 80: Height(19) = 20





